name: time_tracking
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_hooks: ^0.3.0
  rxdart: ^0.22.0
  functional_widget_annotation: ^0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  functional_widget: ^0.6.0
  build_runner: ^1.3.1
flutter:
  uses-material-design: true
